# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Controllers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios', models.CharField(max_length=200)),
                ('controller', models.CharField(max_length=200)),
                ('serial_number', models.CharField(max_length=6)),
                ('numero_sectores', models.CharField(max_length=6)),
                ('web_direction', models.TextField()),
                ('read_control_calendario', models.TextField()),
                ('read_status', models.TextField()),
                ('status_put', models.TextField()),
                ('control_calendario_put', models.TextField()),
                ('read_analog_reading', models.TextField()),
                ('controller_coordinates', models.TextField()),
                ('lat_lng', models.TextField()),
                ('analog_laws', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuarios_correo', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
    ]
